package perry:container;

interface types {
    record container-spec {
        image: string,
        name: option<string>,
        ports: option<list<string>>,
        volumes: option<list<string>>,
        env: option<list<tuple<string, string>>>,
        cmd: option<list<string>>,
        entrypoint: option<list<string>>,
        network: option<string>,
        rm: option<bool>,
    }

    record container-info {
        id: string,
        name: string,
        image: string,
        status: string,
        ports: list<string>,
        created: string,
    }

    record container-logs {
        stdout: string,
        stderr: string,
    }

    record image-info {
        id: string,
        repository: string,
        tag: string,
        size: u64,
        created: string,
    }

    record backend-info {
        name: string,
        available: bool,
        reason: option<string>,
        version: option<string>,
    }
}

world perry-container {
    import types;

    export run: func(spec: types.container-spec) -> result<u64, string>;
    export create: func(spec: types.container-spec) -> result<u64, string>;
    export start: func(id: string) -> result<_, string>;
    export stop: func(id: string, timeout: option<u32>) -> result<_, string>;
    export remove: func(id: string, force: bool) -> result<_, string>;
    export list: func(all: bool) -> result<list<types.container-info>, string>;
    export inspect: func(id: string) -> result<types.container-info, string>;
    export logs: func(id: string, tail: option<u32>) -> result<types.container-logs, string>;
    export exec: func(id: string, cmd: list<string>) -> result<types.container-logs, string>;

    export pull-image: func(reference: string) -> result<_, string>;
    export list-images: func() -> result<list<types.image-info>, string>;
    export remove-image: func(reference: string, force: bool) -> result<_, string>;

    export get-backend: func() -> string;
    export detect-backend: func() -> result<list<types.backend-info>, string>;

    export compose-up: func(spec-json: string) -> result<u64, string>;
    export compose-down: func(handle: u64, volumes: bool) -> result<_, string>;
    export compose-ps: func(handle: u64) -> result<list<types.container-info>, string>;
    export compose-logs: func(handle: u64, service: option<string>) -> result<types.container-logs, string>;
    export compose-exec: func(handle: u64, service: string, cmd: list<string>) -> result<types.container-logs, string>;
}
